name: tf_apply

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone tf source repo
      uses: actions/checkout@v2

    - name: clone tf source repo
      uses: actions/checkout@v2
      with:
        repository: RexBelli/terraform-provider-secberus
        path: "tf-provider-secberus"

    - name: log in to gcp
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1

    - name: setup tf provider
      run: |
        cd tf-provider-secberus
        make install
        cd ..

    - name: run tf plan
      env:
        SECBERUS_USERNAME: ${{ secrets.SECBERUS_USERNAME }}
        SECBERUS_PASSWORD: ${{ secrets.SECBERUS_PASSWORD }}
      run: |
        terraform init
        terraform validate
        terraform plan
      
